### ISSUE TITLE
When can we open source datasets?

### ISSUE THREAD

**Issue by HaungVita** [hlchen23/VERIFIED#1]
I think this is going to be a big contribution to VCMR, and I really want to be able to use this open source data, when will it be made public? Thank you

**Comment by hlchen23** [comment]
您的来件已收到，谢谢！（自动回复）Chen

**Comment by hlchen23** [comment]
Thanks for your attention to our work! I will update this repo soon in this month.

**Comment by HaungVita** [comment]
> Thanks for your attention to our work! I will update this repo soon in this month.
Thanks for your response, I think it's a meaningful piece of work and I'm really looking forward to your dataset

**Comment by wuyuxiangX** [comment]
Thank you for your work in the field of video understanding. Could you please list the files related to the dataset in advance? This will be very helpful for my recent work? @hlchen23

**Comment by LexingtonJd** [comment]
Hello, your work is very interesting. May I ask when you will release the dataset and code?

**Comment by hlchen23** [comment]
您的来件已收到，谢谢！（自动回复）Chen

**Comment by hlchen23** [comment]
Thank you for your attention! The dataset has been released.~

**Comment by hlchen23** [comment]
Features have been released.
